### ISSUE TITLE
Title accuracy.

### ISSUE THREAD

**Issue by farishkash** [aditbal/prj-rev-bwfs-dasmoto#1]
https://github.com/aditbal/prj-rev-bwfs-dasmoto/blob/ad570f0955e2f07612fc97cba6c5b2ba6dca54a0/Project_dasmoto_ac/index.html#L4

The name of the company is  Dasmoto's Arts & Crafts.  The title should match.  The title is used for SEO purposes, plus the name of the site on the tab bar.  Companys/Clients care about accuracy with regards to their name.

**Comment by aditbal** [comment]
will follow your suggestion...

Balaji K
