### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by farishkash** [aditbal/prj-rev-bwfs-dasmoto#2]
Overall met expectations

In this first project, I look at two primary items with the main goal being to stop inefficient or bad practices early.

First, did you use divs, ids/classes to manage and organize your HTML.
Great on this, had everything I look for in this first project.

Second is your CSS efficient and non-repetitive.
Great on this also, you avoided the common mistakes I typically see in this first project.

To prepare you for the upcoming projects I like you to go to flexboxfroggy.com. See how far you can get, the later projects uses flexbox heavily and this will help you immensely.

**Comment by aditbal** [comment]
Thank You farishkash...
Will follow your advice and hope to do better in the upcoming projects...

Balaji K
